--- #YAML:1.0
name: Tie-FieldVals
version: 0.01
author:
  - Kathryn Andersen
abstract: |-
  an array tie for a file of enhanced Field:Value data
license: perl
requires:
  Carp: 0
  Data::Dumper: 0
  Fcntl: 0
  Tie::Array: 0
  Tie::File: 0
build_requires:
  Test::More: 0
provides:
  Tie::FieldVals:
    file: lib/Tie/FieldVals.pm
    version: 0.01
  Tie::FieldVals::Join:
    file: lib/Tie/FieldVals/Join.pm
    version: 0.01
  Tie::FieldVals::Join::Row:
    file: lib/Tie/FieldVals/Join/Row.pm
    version: 0.01
  Tie::FieldVals::Row:
    file: lib/Tie/FieldVals/Row.pm
    version: 0.01
  Tie::FieldVals::Select:
    file: lib/Tie/FieldVals/Select.pm
    version: 0.01
generated_by: Module::Build version 0.26
